### ISSUE TITLE
Support for uniqueidentifiers

### ISSUE THREAD

**Issue by sebbie** [sebbie/SqlQuery#3]
Currently uniqueidentifier fails with "Error converting data type varchar to uniqueidentifier" message:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: System.Exception: SqlCommand='EXEC dbo.GuidTest @guidParam=''' ConnectionString='(redacted)' ---> System.Data.SqlClient.SqlException: Error converting data type varchar to uniqueidentifier.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader()
   at Microsoft.VisualStudio.TextTemplating40D6E0CCC43485BFF51860F2AA60163346760CFBE3B9C549B8A84E9E55F88684882C151DF4BEEB8D6D6C6C3950958DD12C826F3EC86C79F76C8A9D435644F368.GeneratedTextTransformation.SqlQuery.InspectResultSets(String sqlCommand, Action`2 readRow)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.TextTemplating40D6E0CCC43485BFF51860F2AA60163346760CFBE3B9C549B8A84E9E55F88684882C151DF4BEEB8D6D6C6C3950958DD12C826F3EC86C79F76C8A9D435644F368.GeneratedTextTransformation.SqlQuery.InspectResultSets(String sqlCommand, Action`2 readRow)
   at Microsoft.VisualStudio.TextTemplating40D6E0CCC43485BFF51860F2AA60163346760CFBE3B9C549B8A84E9E55F88684882C151DF4BEEB8D6D6C6C3950958DD12C826F3EC86C79F76C8A9D435644F368.GeneratedTextTransformation.SqlQuery.ReadDatabase()
   at Microsoft.VisualStudio.TextTemplating40D6E0CCC43485BFF51860F2AA60163346760CFBE3B9C549B8A84E9E55F88684882C151DF4BEEB8D6D6C6C3950958DD12C826F3EC86C79F76C8A9D435644F368.GeneratedTextTransformation.TransformText()	DAO	...\DAO\SqlQuery.tt	1	
`

**Comment by sebbie** [comment]
Resolved
